version: "3.1"
services:
  web:
    build: .
    container_name: "boot-app"
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mongo
    container_name: "springboot-mongo"
    restart: always
    expose:
      - "27017"
